media:
  input: _src/static/uploads
  output: uploads
content:
  - name: "config"
    label: "Configuratie"
    path: "_src/_data"
    type: collection
    option:
      multiple: true
    fields:
      - name: "settings"
        label: "Site Settings"
        path: "site.yml"
        type: file
        fields:
          - { name: "name", label: "Naam", type: "string" }
          - name: "metas"
            label: "metas"
            type: "object"
            fields:
              - { name: "title", label: "Title", type: "string" }
              - { name: "description", label: "Description", type: "string" }
              - { name: "icon", label: "Icon", type: "image" }
              - { name: "lang", label: "Language", type: "string" }
              - { name: "generator", label: "Generator", type: "boolean" }
        
      - name: "company"
        label: "Company Settings"
        path: "company.yml"
        type: file
        fields:
          - { name: "logo", label: "Logo", type: "image" }
          - { name: "name", label: "Naam", type: "string" }
          - { name: "phone", label: "Telefoon", type: "string" }
          - { name: "email", label: "Email", type: "string" }
          - { name: "kvk_nummer", label: "Kvk nummer", type: "string" }
          - { name: "btw_nummer", label: "BTW nummer", type: "string" }
          - name: "address"
            label: "Adress"
            type: "object"
            fields:
              - { name: "street", label: "Straat", type: "string" }
              - { name: "zipcode", label: "Postcode", type: "string" }
              - { name: "city", label: "Stad", type: "string" }
      
  - name: "pages"
    label: "Pages"
    path: "_src"
    type: collection
    fields:
      - name: "homepage"
        label: "Home page"
        path: "index.md"
        type: file
        fields:
          - { name: title, label: "Pagina title", type: "string" }
          - { name: description, label: "Pagina beschrijving", type: "string" }
    
          - name: "metas"
            label: "metas"
            type: "object"
            fields:
              - { name: "title", label: "Title", type: "string" }
              - { name: "description", label: "Description", type: "string" }
    
          - name: section_hero
            label: Hero Block
            type: object
            fields:
              - { name: "block_title", label: "Block title", type: "string" }
              - { name: "title", label: "Title", type: "string" }
              - { name: "image", label: "Image", type: "image" }
              - { name: "alt", label: "Image description", type: "string" }
    
    
          # - name: section_services
          #   label: Diensten block
          #   type: object
          #   fields:
          #     - { name: "block_title", label: "Block title", type: "string" }
          #     - { name: "title", label: "Title", type: "string" }
          #     - name: "list"
          #       label: "Hoofd diensten"
          #       type: "list"
          #       fields:
          #         - { name: "name", label: "Name", type: "string" }
          #         - { name: "icon", label: "Icon", type: "image" }
          #         - { name: "body", label: "Body", type: "text" }
          #         - { name: "url", label: "Url", type: "string" }
    
    
          - name: section_about
            label: About Block
            type: object
            fields:
              - { name: "block_title", label: "Block title", type: "string" }
              - { name: "title", label: "Title", type: "string" }
              - { name: "image", label: "Image", type: "image" }
              - { name: "alt", label: "Image description", type: "string" }
    
    
          - name: section_gallery
            label: Galerij block
            type: object
            fields:
              - { name: "block_title", label: "Block title", type: "string" }
              - { name: "title", label: "Title", type: "string" }
              - name: "images"
                label: "Gallery images"
                type: image
                options:
                  multiple: true
    
          - name: section_cta
            label: Galerij block
            type: object
            fields:
              - { name: "block_one_title", label: "Block 1 title", type: "string" }
              - { name: "block_one_body", label: "text", type: "text" }
              - name: "button_one"
                label: "Button"
                type: "object"
                fields:
                  - { name: "title", label: "title", type: "string" }
                  - { name: "url", label: "Url", type: "string" }
    
              - { name: "block_two_title", label: "Block 1 title", type: "string" }
              - { name: "block_two_body", label: "text", type: "text" }
              - name: "button_two"
                label: "Button"
                type: "object"
                fields:
                  - { name: "title", label: "title", type: "string" }
                  - { name: "url", label: "Url", type: "string" }
    
      - name: "about"
        label: "About page"
        path: "over-ons.md"
        type: file
        fields:
          - { name: title, label: "Pagina title", type: "string" }
          - { name: description, label: "Pagina beschrijving", type: "string" }
    
          - name: "metas"
            label: "metas"
            type: "object"
            fields:
              - { name: "title", label: "Title", type: "string" }
              - { name: "description", label: "Description", type: "string" }
    
          - name: "section_hero"
            label: "Hero Block"
            type: "object"
            fields:
              - { name: "block_title", label: "Block title", type: "string" }
              - { name: "title", label: "Title", type: "string" }
              - { name: "body", label: "Body", type: "string" }
              - { name: "image", label: "Image", type: "image", default: "/images/undraw_pure-love.svg" }
              - { name: "alt", label: "Image description", type: "string" }
    
    
          - name: "section_one"
            label: "Location Block"
            type: "object"
            fields:
              - { name: "block_title", label: "Block title", type: "string" }
              - { name: "title", label: "Title", type: "string" }
              - { name: "body", label: "Body", type: "string" }
              - { name: "image", label: "Image", type: "image", default: "/images/undraw_partying.svg" }
              - { name: "alt", label: "Image description", type: "string" }
    
          - name: "section_two"
            label: "Team Block"
            type: "object"
            fields:
              - { name: "block_title", label: "Block title", type: "string" }
              - { name: "title", label: "Title", type: "string" }
              - { name: "body", label: "Body", type: "string" }
              - { name: "image", label: "Image", type: "image", default: "/images/undraw_team.svg" }
              - { name: "alt", label: "Image description", type: "string" }
    
    
          - name: "section_three"
            label: "Werkwijzen Block"
            type: "object"
            fields:
              - { name: "block_title", label: "Block title", type: "string" }
              - { name: "title", label: "Title", type: "string" }
              - { name: "body", label: "Body", type: "string" }
              - { name: "image", label: "Image", type: "image", default: "/images/undraw_dreamer.svg" }
              - { name: "alt", label: "Image description", type: "string" }
    
          - name: "section_four"
            label: "Ervaringen Block"
            type: "object"
            fields:
              - { name: "block_title", label: "Block title", type: "string" }
              - { name: "title", label: "Title", type: "string" }
              - { name: "body", label: "Body", type: "string" }
              - { name: "image", label: "Image", type: "image", default: "/images/undraw_effortless-love.svg" }
              - { name: "alt", label: "Image description", type: "string" }
    
      - name: "gallery"
        label: "Gallery"
        path: "galerij.md"
        type: file
        fields:
          - { name: title, label: "Pagina title", type: "string" }
          - { name: description, label: "Pagina beschrijving", type: "string" }
    
          - name: "metas"
            label: "metas"
            type: "object"
            fields:
              - { name: "title", label: "Title", type: "string" }
              - { name: "description", label: "Description", type: "string" }
    
          - name: section_gallery
            label: Galerij block
            type: object
            fields:
              - { name: "block_title", label: "Block title", type: "string" }
              - { name: "title", label: "Title", type: "string" }
              - name: "images"
                label: "Gallery images"
                type: "image"
                options:
                  multiple: true
                  multiple.max: 6
    
    
      - name: "services"
        label: "Services page"
        path: "diensten.md"
        type: file
        fields:
          - { name: title, label: "Pagina title", type: "string" }
          - { name: description, label: "Pagina beschrijving", type: "string" }
    
          - name: "metas"
            label: "metas"
            type: "object"
            fields:
              - { name: "title", label: "Title", type: "string" }
              - { name: "description", label: "Description", type: "string" }
    
          - name: "section_services"
            label: "Services block"
            type: "object"
            fields:
              - { name: "block_title", label: "Block title", type: "string" }
              - { name: "title", label: "Title", type: "string" }
    
    
      - name: "contact"
        label: "Contact page"
        path: "contact.md"
        type: file
        fields:
          - { name: title, label: "Pagina title", type: "string" }
          - { name: description, label: "Pagina beschrijving", type: "string" }
    
          - name: "metas"
            label: "metas"
            type: "object"
            fields:
              - { name: "title", label: "Title", type: "string" }
              - { name: "description", label: "Description", type: "string" }
    
          - { name: body, label: "content", type: "text" }
    
    
      - name: "offerte"
        label: "Quote page"
        path: "offerte.md"
        type: file
        fields:
          - { name: title, label: "Pagina title", type: "string" }
          - { name: description, label: "Pagina beschrijving", type: "string" }
    
          - name: "metas"
            label: "metas"
            type: "object"
            fields:
              - { name: "title", label: "Title", type: "string" }
              - { name: "description", label: "Description", type: "string" }
    
          - name: "section_offerte"
            label: "Offerte block"
            type: "object"
            fields:
              - { name: "block_title", label: "Block title", type: "string" }
              - { name: "title", label: "Title", type: "string" }


  - name: "algemene-voorwaarden"
    label: "Algemene voorwaarden"
    path: "algemene-voorwaarden.md"
    type: file
    fields:
      - { name: "title", label: "Title", type: "string" }
      - { name: "description", label: "Description", type: "string" }

      - name: "metas"
        label: "metas"
        type: "object"
        fields:
          - { name: "title", label: "Title", type: "string" }
          - { name: "description", label: "Description", type: "string" }

      - { name: "body", label: "Body", type: rich-text }



  - name: "diensten"
    label: "Services"
    path: "_src/diensten"
    type: collection
    view:
      fields: [ image, title ]
    fields:
      - { name: "order", label: "Volgorde nummer", type: "string" }
      - { name: "title", label: "Title", type: "string" }
      - { name: "description", label: "Description", type: "text" }
      - { name: "image", label: "Image", type: "image" }
      - { name: "body", label: "Body", type: rich-text }
      - { name: "draft", label: "Published", type: "boolean", default: true }
